### ISSUE TITLE
Slf4j wrapped loggers missing in stack trace error

### ISSUE THREAD

**Issue by re-thc** [tinylog-org/tinylog#191] opened 2021-01-09 04:11 UTC
Have tinylog in the classpath with a tinylog.properties file. Run an application with a logging wrapper that uses slf4j, e.g. Vertx.

Result:

Exception in thread "main" java.lang.IllegalStateException: Logger class "io.vertx.core.logging.Logger" is missing in stack trace
	at org.tinylog.runtime.ModernJavaRuntime$DynamicStackFrameExtractor.apply(ModernJavaRuntime.java:159)
	at org.tinylog.runtime.ModernJavaRuntime$DynamicStackFrameExtractor.apply(ModernJavaRuntime.java:129)
	at java.base/java.lang.StackStreamFactory$StackFrameTraverser.consumeFrames(StackStreamFactory.java:534)
	at java.base/java.lang.StackStreamFactory$AbstractStackWalker.doStackWalk(StackStreamFactory.java:306)
	at java.base/java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk(Native Method)
	at java.base/java.lang.StackStreamFactory$AbstractStackWalker.beginStackWalk(StackStreamFactory.java:370)
	at java.base/java.lang.StackStreamFactory$AbstractStackWalker.walk(StackStreamFactory.java:243)
	at java.base/java.lang.StackWalker.walk(StackWalker.java:498)
	at org.tinylog.runtime.ModernJavaRuntime.getCallerStackTraceElement(ModernJavaRuntime.java:76)
	at org.tinylog.runtime.RuntimeProvider.getCallerStackTraceElement(RuntimeProvider.java:126)
	at org.tinylog.core.TinylogLoggingProvider.log(TinylogLoggingProvider.java:160)
	at org.tinylog.slf4j.TinylogLogger.log(TinylogLogger.java:501)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:188)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:160)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:156)
	at io.vertx.core.logging.SLF4JLogDelegate.info(SLF4JLogDelegate.java:104)
	at io.vertx.core.impl.logging.LoggerAdapter.info(LoggerAdapter.java:64)
	at io.vertx.core.impl.launcher.commands.Watcher.<init>(Watcher.java:76)
	at io.vertx.core.impl.launcher.commands.RunCommand.initializeRedeployment(RunCommand.java:288)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:273)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:383)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.vertx.core.Launcher.main(Launcher.java:45)

**Comment by pmwmedia** [comment] 2021-01-09 08:58
Could you provide a minimal example project for reproducing this issue?

**Comment by pmwmedia** [comment] 2021-02-20 16:55
The cause for the exception is that Vertex uses SLF4J's LocationAwareLogger class incorrectly. LocationAwareLogger expects the actual class name of Vertex's logger class "io.vertx.core.impl.logging.LoggerAdapter". However, Vertex provides it's interface "io.vertx.core.logging.Logger" instead. This cannot work neither in tinylog nor Logback.

Logback example:
```xml
<configuration>
  <appender class="ch.qos.logback.core.ConsoleAppender" name="STDOUT">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%t] %-5level %class.%method:%line - %msg%n</pattern>
    </encoder>
  </appender>
  <root level="INFO">
    <appender-ref ref="STDOUT"/>
  </root>
</configuration>
```
```java
public class Application {

  public static void main(String[] args) {
    System.setProperty("vertx.logger-delegate-factory-class-name", SLF4JLogDelegateFactory.class.getName());
    io.vertx.core.impl.logging.LoggerFactory.getLogger(Application.class).info("Hello Vertex!");
    org.slf4j.LoggerFactory.getLogger(Application.class).info("Hello SLF4J!");
  }

}
```

Output:
```
17:36:35.998 [main] INFO  ?.?:? - Hello Vertex!
17:36:36.002 [main] INFO  com.example.starter.Application.main:10 - Hello SLF4J!
```

This issue has to be fixed by Vertex. They have simply to provide "io.vertx.core.impl.logging.LoggerAdapter" instead of "io.vertx.core.logging.Logger" to their LocationAwareLogger implementation.

@hc-codersatlas: In the meantime, you could use JULLogDelegateFactory in Vertex along with `jul-tinylog` as workaround.

However, tinylog should not throw an exception when a wrong logger class is provided. This should be fixed by logging just a warning or ignoring it like Logback.

**Closed as completed** 2021-02-20 19:23 UTC
Labels: bug

**Comment by re-thc** [comment] 2021-02-21 01:59
Thanks for looking into it. Hopefully this fixes the other cases too. Never had a chance to replicate it. Might file the bug with Vertx as per your findings if you haven't.

**Comment by pmwmedia** [comment] 2021-02-21 09:38
I think it is a good idea to file the issue there, Especially it is very trivial to fix it and also other logging frameworks would benefit from the fix.
